// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7srtjXs1NBCbwq5WttsjhBtXbnjjelk',
    appId: '1:206897169781:web:47b848166499cb9fddff3c',
    messagingSenderId: '206897169781',
    projectId: 'diagora---mobile',
    authDomain: 'diagora---mobile.firebaseapp.com',
    storageBucket: 'diagora---mobile.appspot.com',
    measurementId: 'G-911CLSDR2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoLV3Jd14xrA3DDwSB6qvw4gJcJqnGXQ',
    appId: '1:206897169781:android:b75a5b8b8ba9dcddddff3c',
    messagingSenderId: '206897169781',
    projectId: 'diagora---mobile',
    storageBucket: 'diagora---mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARyZOy-3vzT9QmL31VAO7CGQCEGSP2ZfM',
    appId: '1:206897169781:ios:c01a8d691c094984ddff3c',
    messagingSenderId: '206897169781',
    projectId: 'diagora---mobile',
    storageBucket: 'diagora---mobile.appspot.com',
    iosClientId: '206897169781-182rmicrkc5vivg6b99ood96e1fjkvbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.diagora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARyZOy-3vzT9QmL31VAO7CGQCEGSP2ZfM',
    appId: '1:206897169781:ios:c01a8d691c094984ddff3c',
    messagingSenderId: '206897169781',
    projectId: 'diagora---mobile',
    storageBucket: 'diagora---mobile.appspot.com',
    iosClientId: '206897169781-182rmicrkc5vivg6b99ood96e1fjkvbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.diagora',
  );
}
